### ISSUE TITLE
No hide WooCommerce notice

### ISSUE THREAD

**Issue by Iraecio** [oliverschloebe/disable-wordpress-updates#4]
No hide WooCommerce data update
![sem titulo](https://user-images.githubusercontent.com/8146933/38859094-454206aa-41fb-11e8-8ce0-f450bcc9be33.png)

**Comment by Iraecio** [comment]
yes plugin enabled.

woocommerce helper update is

[https://github.com/woocommerce/woocommerce/blob/master/includes/admin/helper/class-wc-helper-updater.php](url)

**Comment by OliverSchloebe** [comment]
Hi Iraecio,

sorry for the late reply, but GDPR is keeping me busy...

I just had a closer look at the update nag you're getting and I'm afraid to say that we can't get rid of that with a plugin. All WooCommerce does there is, that they're checking the plugin version against an option value in the database. If it's different (e.g. after an update) it displays the update nag: https://github.com/woocommerce/woocommerce/blob/9679e7be1fe383b8df78b7874a917f9bcd0eed2f/includes/admin/class-wc-admin-notices.php#L219

As for the actual WordPress background updater, I've created an updated version. May you please [install and try](https://www.dropbox.com/s/m7ez0r5lk4f9lzd/disable-wordpress-updates.zip?dl=1) the new version to check if it's prepending WooCommerce from updating?

Thank you!
