### ISSUE TITLE
What does this plugin do more than using 'DISALLOW_FILE_MODS' in wp-config.php?

### ISSUE THREAD

**Issue by leojonathanoh** [oliverschloebe/disable-wordpress-updates#5]
From my understanding from [Wordpress docs](https://codex.wordpress.org/Editing_wp-config.php), `define( 'DISALLOW_FILE_MODS', true );` used in `wp-config.php` disables theme and plugin updates. But there isn't much documentation about what it does specifically.

Based on the description of this plugin, it also disables crons associated with updating plugin/themes. But what else does it do more than disabling crons?

For non-developers I see the benefit of having a plugin so to manage and manually update a production site by first turning this plugin off, then re-enabling the plugin when updates are done.

**Comment by lkraav** [comment]
I've tested both.

Killing crons and hooks is important because otherwise you will still have tens of plugins, incl commercials, triggering their update check hooks whenever, slowing down admin page load.

I have system cron set up to trigger `wp --skip-plugins=disable-wordpress-updates` daily and that's much better for admin sanity.

**Comment by leojonathanoh** [comment]
@lkraav cool, thanks for the quick response. I haven't been using WP-CLI since I've been out of touch with Wordpress for some time. But that will be handy when I start using it very soon. Definitely post back if I find any more differences 😃

**Comment by lkraav** [comment]
Yep, disabling web-based cron towards system cron + `wp cron event run --due-now` is a big step towards sanity.

**Comment by leojonathanoh** [comment]
wow, that's a neat trick. I'll definitely try that one out 👊
